#FROM alpine/git:latest
#WORKDIR /
#RUN git clone https://github.com/leapsecurity/libssh-scanner

FROM python:3.8-alpine
#COPY --from=0 /clone-workspace/libssh-scanner /bin/libssh-scanner
COPY libssh-scanner /bin/libssh-scanner
RUN apk add --update --no-cache libffi-dev  build-base \
 && rm -rf /var/cache/apk/* 
RUN pip install -r /bin/libssh-scanner/requirements.txt
ENTRYPOINT python3 /bin/libssh-scanner/libsshscan.py -p 2222 127.0.0.1
