---
# file : _packages_install_pip.yml
# description : install python (pip) package 

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

## Check if pip is already installed
- name : Make sur pip is installed
  ansible.builtin.apt:
    update_cache: yes 
    name: pip
    state: latest
  when: "'pip' not in ansible_facts.packages"
  register: pip_installed
  
- name: Install python package with pip
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
  when : pip_installed
