---
# Description : Start influxdb container
# file : _influxdb_container.yml

# docker run --name influxdb -p 8086:8086 --volume $PWD:/var/lib/influxdb2 --net=influxdb-net -d influxdb:2.1.1
- name: Start a influxdb container
  community.docker.docker_container:
    name: influxdb
    image: "{{ influxdb_docker_image }}"
    state: started
    labels: docker.group="test"
    detach: yes
    auto_remove: true
    recreate: true
    published_ports:
      - 0.0.0.0:8086:8086
    volumes:
      - "{{ influxdb_volume_root_directory }}:/var/lib/influxdb2"
    networks:
      - name: "{{ docker_network_name }}"
    comparisons:
      volumes: allow_more_present   # if there are more volumes, that's ok
  register: influxdb
  until: influxdb.container.State.Status == "running"
  retries: 15
  delay: 10
  
#see returned values at : https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
# - name: debbug in order to get the container status
#   ansible.builtin.debug:
#     msg: "{{ nginx.container.State.Status }}"

- name: Check database presence
  uri:
    url: "http://127.0.0.1:8086/query"
    method: POST
    body: 'q=SHOW DATABASES'
  register: response

- name: Create database
  uri:
    url: "http://127.0.0.1:8086/query"
    method: POST
    body: 'q=CREATE DATABASE "{{ influxdb_dbname }}"'
  register: response
  changed_when: response.status == 200
  when: "influxdb_dbname not in response.json | json_query('results[0].series[0].values[*][0]')"