---
# Description : Start nginx container
# file : _nginx_container.yml

- name: Copy the telegraf var file into {{ nginx_volume_root_directory }}
  copy:
    src: "nginx/index.html"
    dest: "{{ nginx_volume_root_directory }}/index.html"
    owner: telegraf
    mode: 0644 
    force: yes

# docker run --rm --name some-nginx -v /some/content:/usr/share/nginx/html:ro -d nginx
- name: Start a nginx container
  community.docker.docker_container:
    name: nginx-1
    image: nginx
    state: started
    labels: docker.group="test"
    detach: yes
    # auto_remove: true
    # recreate: true
    published_ports:
      - 0.0.0.0:8080:80
    volumes:
      - "{{ telegraf_volume_root_directory }}/index.html:/usr/share/nginx/html"
  register: nginx
  # until: nginx.container.State.Status == "running"
  # retries: 15
  # delay: 20
  
# # see returned values at : https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
- name: debbug in order to get the container status
  ansible.builtin.debug:
    msg: "{{ nginx.container.State.Status }}"