---
# Description : Start nginx container
# file : main.yml

- name: copy bashrc
  ansible.builtin.copy:
    src: bashrc
    dest: "/home/{{ user }}/.bashrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'

# docker run --rm --name some-nginx -v /some/content:/usr/share/nginx/html:ro -d nginx
- name: Start a nginx container
  community.docker.docker_container:
    name: nginx-1
    image: nginx
    state: started
    detach: yes
    # auto_remove: true
    # recreate: true
    published_ports:
      - 0.0.0.0:8080:80
    # mount:
    #   # - label: nginx_volume
    #   - read_only: true
    #   - source: "./index.html"
    #   - target: "/usr/share/nginx/html"
  register: nginx

# see return values at : https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
- name: debbug in order to get the container status
  ansible.builtin.debug:
    msg: "{{ nginx.container.State.Status }}"