- hosts: all 
  gather_facts: true

  tasks:
    - name: Set timezone to Europe/London
      become: yes
      timezone:
        name: Europe/London
  roles:
    # - role: install_packages
    #   become: true
    #   tags: [install_packages]
    
    # Install docker
    - role: docker_server
      tags: [docker_server] 

    # Start nginx container
    - role: docker_container
      tags: [docker_container] 

    # Install Telegraf (monitoring Docker Engine Host and the nginx container)
    # - role: influxdb_server
    #   tags: [influxdb_server]

    # # Install Influxdb
    # - role: telegraf_server
    #   # become: true
    #   tags: [telegraf_server]

    # # Install Grafana
    # - role: grafana_server
    #   # become: true
    #   tags: [grafana_server] 
