---
dependencies:
  - role: install_packages
    become: yes
    vars:
      apt_repo_key :
        - {"url" : "https://repos.influxdata.com/influxdb.key", "dest" : "/usr/share/keyrings/influxdb.asc"}
      apt_repo:
        - "deb [signed-by=/usr/share/keyrings/influxdb.asc] https://repos.influxdata.com/{{ ansible_facts['distribution']|lower }} {{ ansible_distribution_release }} stable"
        # - "deb [signed-by=/usr/share/keyrings/hashicorp.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }}  main"
      apt_packages_list:
        - influxdb